footprint: [[-0.156,-0.31], [0.156, -0.31], [0.558, -0.24], [0.558, 0.24], [0.156, 0.31], [-0.156,0.31]]
footprint_padding: 0.05

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.3

resolution: 0.05

obstacle_range: 4.5
raytrace_range: 8.5

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.2
#sonar_layer:
#  topics: ["/sonar_0"]
#  no_readings_timeout: 2.0
#  clear_threshold: 0.05
#  mark_threshold: 0.15

