################################################################################
# configuring the global planner global_planner/GlobalPlanner by explicitly    #
# stating defauls and tunning a few parameters as per Kaiyu Zheng              #
################################################################################


# namespace for the parameters that the global_planner node exposes. See: 
# https://wiki.ros.org/global_planner   specifically section 4.0 ROS API
GlobalPlanner:
#----------------------------------DEFAULT--------------------------------------
  # Specifies whether or not to allow the planner to create plans that traverse 
  # unknown space. NOTE: if you are using a layered costmap_2d costmap with a voxel 
  # or obstacle layer, you must also set the track_unknown_space param for that layer 
  # to be true, or it will convert all your unknown space to free space (which   
  # planner will then happily go right through). 
  allow_unknown: true 

  #If true, use dijkstra's algorithm. Otherwise, A*.
  use_dijkstra: true 

  #If true, use the quadratic approximation of the potential. Otherwise, use a simpler calculation. 
  use_quadratic: true

  #If true, create a path that follows the grid boundaries. Otherwise, use a gradient descent method. 
  use_grid_path: false

  #If for some reason, you want global_planner to exactly mirror the behavior of 
  #navfn, set this to true (and use the defaults for the other boolean parameters) 
  old_navfn_behavior: false

  #Specifies whether or not to visualize the potential area computed via a 
  #PointCloud2. Set true to see in RViz.
  visualize_potential: true

  #A tolerance on the goal point for the planner. The planner will attempt to 
  #create a plan that is as close to the specified goal as possible but no 
  #further than default_tolerance away. 
  # default_tolerance: 0.1 #default is 0.0 but that is too strict.

#----------------------------------TUNED----------------------------------------
  #Factor to multiply each cost from costmap by (dynamic reconfigure). default is 3
  cost_factor: 0.55 

  # Neutral Cost (dynamic reconfigure). default is 50 
  neutral_cost: 66

  # Lethal Cost (dynamic reconfigure)  
  lethal_cost: 253 # default




