local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  rolling_window: false

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  width: 3
  height: 3
  resolution: 0.25

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  # - {name: sonar_layer,               type: "range_sensor_layer::RangeSensorLayer"}
