uint8 order
string label
string backgroundColor
string borderColor
uint8[] borderDash
uint8 borderWidth
string pointBackgroundColor
string pointBorderColor
string pointBorderWidth
string pointRadius
# pointStyle can be 'circle', 'cross', 'crossRot', 'dash', 'line', 'rect', 'rectRounded', 'rectRot', or 'star'
string pointStyle
float32 lineTension
# z field in geometry_msgs/Point is ignored
geometry_msgs/Point[] data