footprint: [[-0.156,-0.31], [0.156, -0.31], [0.558, -0.24], [0.558, 0.24], [0.156, 0.31], [-0.156,0.31]]

transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0

#must match incoming static map
global_frame: map
robot_base_frame: base_link
resolution: 0.05

rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: polygon_layer,    type: "polygon_layer::PolygonLayer"}
  #Can disable sensor layer if gmapping is fast enough to update scans
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}
  - {name: sonar_layer,            type: "range_sensor_layer::RangeSensorLayer"}

static:
#Can pull data from gmapping, map_server or a non-rolling costmap
  map_topic: /map
  # map_topic: move_base/global_costmap/costmap
  subscribe_to_updates: true

polygon_layer:
  resize_to_polygon: true

sensor:
  observation_sources: laser
  laser: {sensor_frame: ce30c_lidar, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, raytrace_range: 1.0, obstacle_range: 1.0}

inflation:
  inflation_radius: 0.2
sonar_layer:
 topics: ["ultrasound_center", "ultrasound_left_top", "ultrasound_left_back", "ultrasound_left_back_back", "ultrasound_right_top", "ultrasound_right_back", "ultrasound_right_back_back"]
 no_readings_timeout: 2.0
 clear_threshold: 0.05
 mark_threshold: 0.15