analyzers:
  engix:
    type: diagnostic_aggregator/GenericAnalyzer
    path: engix_robot
    find_and_remove_prefix: 'engix_base: '
    expected: ['engix_base: power_status','engix_base: system_status','engix_base: safety_status','engix_base: software_status']
    timeout: 5.0
